import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Menu from "../src/componants/Menu";
import { menuItemsMock } from "../src/componants/Menu/mock";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Menu menuItems={menuItemsMock} style={defaultStyle} />
      </main>
    </>
  );
}

const colorStyle = {
  // border: "solid 1px black",
};

const dimensionStyle = {
  width: "200px",
  height: "200px",
};

const defaultStyle = { ...colorStyle, dimensionStyle };
